name: Tensil

on: workflow_dispatch

env:
  SABANA_ACCESS_TOKEN: ${{secrets.SABANA_ACCESS_TOKEN}}
  SABANA_ID_TOKEN: ${{secrets.SABANA_ID_TOKEN}}

jobs:
  run-tensil-diagnostics:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install pytest sabana==0.1.24
      - name: Run Tensil Diagnostic tests
        working-directory: ./tensil/tests
        run: bash diagnostics.sh
