name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SABANA_ACCESS_TOKEN: ${{secrets.SABANA_ACCESS_TOKEN}}
  SABANA_ID_TOKEN: ${{secrets.SABANA_ID_TOKEN}}

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Black lint
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  run-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install pytest sabana==0.1.24
      - name: Run examples
        working-directory: ./
        # Do not include any examples with external dependencies here.
        # Add a separate workflow, see pyrtl.yml for reference.
        run: pytest --ignore=pyrtl_muladd --ignore=tensil --ignore=3rd_party .
